# Generated by Django 4.0.5 on 2022-06-12 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_companyevents_rename_time_created_event_created_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="end",
        ),
        migrations.RemoveField(
            model_name="event",
            name="start",
        ),
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="updated_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="updated_time",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(2022, 6, 12, 11, 30, 25, 718063),
            ),
            preserve_default=False,
        ),
    ]
